version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: childmarket
      POSTGRES_USER: childmarket
      POSTGRES_PASSWORD: childmarket
    ports:
      - 5432:5432